# Generated by Django 2.2.12 on 2020-12-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_smartsearch.fields
import tcc_kiola_medication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kiola_senses', '0082_auto_20200625_0850_part2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiola_med', '0010_compound_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TakingFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of last update to index element.')),
                ('data', django_smartsearch.fields.JSONField(default=tcc_kiola_medication.models.element_default, help_text='The actual data of the index entry.')),
                ('user', models.OneToOneField(help_text="Owner of the index element. If the referenced model instance has a reference to Django's user model. It is most likely that these fields are equal.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTaking',
            fields=[
                ('basetaking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiola_med.BaseTaking')),
                ('taking_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dosage', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('hint', models.TextField()),
                ('reminder', models.BooleanField(default=False)),
                ('clinic_scheduled', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.TakingFrequency')),
                ('timepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.TakingTimepoint')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_med.TakingUnit')),
            ],
            bases=('kiola_med.basetaking',),
        ),
        migrations.CreateModel(
            name='PatientAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='c1637011-fa24-46a4-8f25-13d7a8e76139', max_length=100)),
                ('substance', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.AdverseReactionType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_senses.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRelatedHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Timestamp of data created.')),
                ('data', django_smartsearch.fields.JSONField(default=tcc_kiola_medication.models.element_default, help_text='Data of changes to content_object.')),
                ('content_type', models.ForeignKey(blank=True, help_text='Model type of the target object. ', null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='58b0dc56-855b-4a87-ae33-88bcc2089512', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Compound')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.AdverseReactionType')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Prescription')),
            ],
            options={
                'unique_together': {('prescription', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CompoundExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Compound')),
            ],
            options={
                'unique_together': {('compound', 'name')},
            },
        ),
    ]
