# Generated by Django 2.2.12 on 2020-11-24 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_smartsearch.fields
import tcc_kiola_medication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiola_senses', '0082_auto_20200625_0850_part2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiola_med', '0010_compound_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TakingFrequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferenceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Timestamp of last update to index element.')),
                ('data', django_smartsearch.fields.JSONField(default=tcc_kiola_medication.models.element_default, help_text='The actual data of the index entry.')),
                ('user', models.OneToOneField(help_text="Owner of the index element. If the referenced model instance has a reference to Django's user model. It is most likely that these fields are equal.", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTaking',
            fields=[
                ('basetaking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiola_med.BaseTaking')),
                ('taking_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('dosage', models.TextField()),
                ('strength', models.CharField(max_length=100)),
                ('reminder', models.BooleanField(default=False)),
                ('clinic_scheduled', models.BooleanField(default=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.TakingFrequency')),
                ('timepoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.TakingTimepoint')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_med.TakingUnit')),
            ],
            bases=('kiola_med.basetaking',),
        ),
        migrations.CreateModel(
            name='PatientAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='8d61595c-6b5f-4965-bb06-7f4b28808610', max_length=100)),
                ('substance', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.AdverseReactionType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_senses.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='8538a3f1-a2c1-41e1-ba02-92f5866a7201', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Compound')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.AdverseReactionType')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Compound')),
            ],
        ),
    ]
