# Generated by Django 2.2.12 on 2020-11-17 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kiola_med', '0010_compound_registration_number'),
        ('kiola_senses', '0082_auto_20200625_0850_part2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='50b37574-3ea9-4d80-959a-df38fe109530', max_length=100)),
                ('substance', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.AdverseReactionType')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_senses.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdverseReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='d758d64f-4962-448b-ac8b-6a68620bc887', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reactions', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiola_med.Compound')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
