# Generated by Django 2.2.12 on 2020-11-13 06:57

from django.db import migrations


def addAdverseReactionTypes(apps, schema_editor):
    from tcc_kiola_medication import const, models

    models.AdverseReactionType.objects.get_or_create(
        name=const.ADVERSE_REACTION_TYPE__ALLERGY
    )
    models.AdverseReactionType.objects.get_or_create(
        name=const.ADVERSE_REACTION_TYPE__IDIOSYNCRATIC
    )
    models.AdverseReactionType.objects.get_or_create(
        name=const.ADVERSE_REACTION_TYPE__INTOLERANCE
    )
    models.AdverseReactionType.objects.get_or_create(
        name=const.ADVERSE_REACTION_TYPE__SIDE_EFFECT
    )
    models.AdverseReactionType.objects.get_or_create(
        name=const.ADVERSE_REACTION_TYPE__UNKNOWN
    )


def undo_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tcc_kiola_medication", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(addAdverseReactionTypes, undo_noop),
    ]
