# Generated by Django 2.2.12 on 2020-12-16 03:22

from django.db import migrations


def data_import(apps, schema_editor):
    import os
    from reversion import revisions as reversion
    from django.core.files.uploadedfile import SimpleUploadedFile
    from kiola.utils.commons import get_system_user
    from tcc_kiola_medication.forms import CompoundImportHistoryForm

    module_dir = os.path.dirname(__file__) # get current directory
    module_dir = module_dir.replace("/migrations", "") 
    file_path = os.path.join(module_dir, 'datafiles/data/mos_rx.csv')
    with reversion.create_revision():
        reversion.set_user(get_system_user())
        with open(file_path, 'rb') as fp:
            form = CompoundImportHistoryForm(
                                              data={ "data_source_description": "mos_rx.csv TCC", "data_source_version": "1.21"}, 
                                              files={"source_file": SimpleUploadedFile('mos_rx_1000_rows.csv', fp.read())}
                                            )
            form.is_valid()
            form.save()

def undo_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tcc_kiola_medication', '0004_add_med_obs_profile_20201207_1607'),
    ]

    operations = [
        migrations.RunPython(data_import, undo_noop),
    ]
