# Generated by Django 2.2.12 on 2021-04-23 04:34

from django.db import migrations



def setup_med_obs_profile(apps, schema_editor):
    from django.contrib.auth.models import Group
    from reversion import revisions as reversion
    from kiola.utils.commons import get_system_user
    from kiola.kiola_senses import const
    from .. import pyxtures

    if Group.objects.filter(name=const.USER_GROUP__DEVICE_MANAGERS).count() > 0:
        with reversion.create_revision():
            reversion.set_user(get_system_user())
            pyxtures.Pyxture().setup_medication_observation_profile()

def undo_noop(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tcc_kiola_medication', '0005_auto_20210112_1746'),
    ]

    operations = [
        migrations.RunPython(setup_med_obs_profile, undo_noop),
    ]
