# Generated by Django 2.2.12 on 2021-06-17 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiola_med', '0010_compound_registration_number'),
        ('tcc_kiola_medication', '0007_default_med_list_config_20210610_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TCCPrescription',
            fields=[
                ('prescription_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kiola_med.Prescription')),
                ('dosage', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=100)),
                ('medication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tcc_kiola_medication.MedicationType')),
                ('takings', models.ManyToManyField(related_name='takings_set', to='tcc_kiola_medication.ScheduledTaking')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kiola_med.TakingUnit')),
            ],
            bases=('kiola_med.prescription',),
        ),
    ]
