# Generated by Django 2.2.12 on 2021-07-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc_kiola_medication', '0009_auto_20210617_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tccprescription',
            name='dosage',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tccprescription',
            name='strength',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
